name: first_app_flutter
description: Mobilna aplikacija za pregled i upravljanje kozmetiÄkim proizvodima
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_database: ^10.2.2
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.5

  # UI i slike
  flutter_svg: ^2.2.3
  carousel_slider: ^5.1.1
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0

  # State management
  provider: ^6.1.5+1

  # Ostalo
  intl: ^0.19.0
  url_launcher: ^6.3.2
  smooth_page_indicator: ^1.0.0+2  # za dots indicator

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/images/logo2.jpg
    - assets/images/adora.jpg
    - assets/images/bannerno1.jpg
    - assets/images/bannerno2.jpg
    - assets/images/splash.jpg
    - assets/images/profilepic.jpg
    - assets/images/korpa.jpg
    - assets/images/boxes.jpg
    - assets/images/users5.jpg

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf
    - family: Spinnaker
      fonts:
        - asset: assets/fonts/Spinnaker-Regular.ttf
